// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mailing.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type From struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *From) Reset()         { *m = From{} }
func (m *From) String() string { return proto.CompactTextString(m) }
func (*From) ProtoMessage()    {}
func (*From) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2cecc45ceda4621, []int{0}
}

func (m *From) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_From.Unmarshal(m, b)
}
func (m *From) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_From.Marshal(b, m, deterministic)
}
func (m *From) XXX_Merge(src proto.Message) {
	xxx_messageInfo_From.Merge(m, src)
}
func (m *From) XXX_Size() int {
	return xxx_messageInfo_From.Size(m)
}
func (m *From) XXX_DiscardUnknown() {
	xxx_messageInfo_From.DiscardUnknown(m)
}

var xxx_messageInfo_From proto.InternalMessageInfo

func (m *From) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *From) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *From) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type To struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *To) Reset()         { *m = To{} }
func (m *To) String() string { return proto.CompactTextString(m) }
func (*To) ProtoMessage()    {}
func (*To) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2cecc45ceda4621, []int{1}
}

func (m *To) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_To.Unmarshal(m, b)
}
func (m *To) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_To.Marshal(b, m, deterministic)
}
func (m *To) XXX_Merge(src proto.Message) {
	xxx_messageInfo_To.Merge(m, src)
}
func (m *To) XXX_Size() int {
	return xxx_messageInfo_To.Size(m)
}
func (m *To) XXX_DiscardUnknown() {
	xxx_messageInfo_To.DiscardUnknown(m)
}

var xxx_messageInfo_To proto.InternalMessageInfo

func (m *To) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *To) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Body struct {
	DataType             string   `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2cecc45ceda4621, []int{2}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Body) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SendRequest struct {
	From                 *From    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   *To      `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 *Body    `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2cecc45ceda4621, []int{3}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetFrom() *From {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SendRequest) GetTo() *To {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendRequest) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

type SendResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f2cecc45ceda4621, []int{4}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*From)(nil), "mailing.v1.From")
	proto.RegisterType((*To)(nil), "mailing.v1.To")
	proto.RegisterType((*Body)(nil), "mailing.v1.Body")
	proto.RegisterType((*SendRequest)(nil), "mailing.v1.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "mailing.v1.SendResponse")
}

func init() {
	proto.RegisterFile("mailing.proto", fileDescriptor_f2cecc45ceda4621)
}

var fileDescriptor_f2cecc45ceda4621 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xb1, 0x4e, 0xe3, 0x40,
	0x10, 0x86, 0x65, 0x9f, 0x2f, 0x97, 0x4c, 0x72, 0xd1, 0xdd, 0x0a, 0x11, 0x2b, 0x20, 0x04, 0x06,
	0x21, 0x44, 0x61, 0x2b, 0xa1, 0x40, 0xa2, 0x4c, 0x41, 0x05, 0x8d, 0x93, 0x8a, 0x06, 0xad, 0xe3,
	0xc1, 0x18, 0xc5, 0x3b, 0xc6, 0xbb, 0xb6, 0xe4, 0x96, 0x57, 0xc8, 0xa3, 0xf1, 0x0a, 0x3c, 0x08,
	0xda, 0xb5, 0x03, 0x91, 0xd2, 0x50, 0x79, 0xfe, 0x99, 0xf9, 0x3f, 0xcf, 0xaf, 0x85, 0xbf, 0x19,
	0x4f, 0x57, 0xa9, 0x48, 0xfc, 0xbc, 0x20, 0x45, 0x0c, 0x36, 0xb2, 0x9a, 0x8c, 0x0f, 0x13, 0xa2,
	0x64, 0x85, 0x01, 0xcf, 0xd3, 0x80, 0x0b, 0x41, 0x8a, 0xab, 0x94, 0x84, 0x6c, 0x36, 0xbd, 0x3b,
	0x70, 0x6e, 0x0b, 0xca, 0xd8, 0x1e, 0xfc, 0x46, 0x6d, 0x72, 0xad, 0x63, 0xeb, 0xa2, 0x17, 0x36,
	0x82, 0x31, 0x70, 0x04, 0xcf, 0xd0, 0xb5, 0x4d, 0xd3, 0xd4, 0x6c, 0x0c, 0xdd, 0x52, 0x62, 0x61,
	0xfa, 0xbf, 0x4c, 0xff, 0x4b, 0x7b, 0x3e, 0xd8, 0x0b, 0xfa, 0x39, 0xcb, 0xbb, 0x06, 0x67, 0x46,
	0x71, 0xcd, 0x0e, 0xa0, 0x17, 0x73, 0xc5, 0x1f, 0x55, 0x9d, 0x63, 0xeb, 0xea, 0xea, 0xc6, 0xa2,
	0xce, 0x51, 0x1b, 0x75, 0xbd, 0x31, 0xea, 0xda, 0x5b, 0x5b, 0xd0, 0x9f, 0xa3, 0x88, 0x43, 0x7c,
	0x2d, 0x51, 0x2a, 0x76, 0x06, 0xce, 0x53, 0x41, 0x99, 0xf1, 0xf6, 0xa7, 0xff, 0xfc, 0xef, 0xfc,
	0xbe, 0x8e, 0x17, 0x9a, 0x29, 0x3b, 0x02, 0x5b, 0x91, 0xe1, 0xf4, 0xa7, 0xc3, 0xed, 0x9d, 0x05,
	0x85, 0xb6, 0x22, 0xe6, 0xc2, 0x1f, 0x59, 0x46, 0x2f, 0xb8, 0x54, 0x6d, 0xb2, 0x8d, 0xd4, 0xfc,
	0x88, 0xe2, 0xda, 0x75, 0x76, 0xf9, 0x3a, 0x40, 0x68, 0xa6, 0xde, 0x39, 0x0c, 0x9a, 0xa3, 0x64,
	0x4e, 0x42, 0x22, 0xdb, 0x87, 0x8e, 0x54, 0x5c, 0x95, 0xd2, 0xdc, 0xd5, 0x0d, 0x5b, 0x35, 0x8d,
	0x61, 0x78, 0xdf, 0x00, 0xe6, 0x58, 0x54, 0xe9, 0x12, 0x59, 0x08, 0x8e, 0x76, 0xb2, 0xd1, 0x36,
	0x79, 0x2b, 0xe0, 0xd8, 0xdd, 0x1d, 0x34, 0x3f, 0xf1, 0x46, 0x6f, 0xef, 0x1f, 0x6b, 0xfb, 0xbf,
	0x37, 0x08, 0xaa, 0x49, 0x20, 0x51, 0xc4, 0x7a, 0xf1, 0xc6, 0xba, 0x9c, 0x9d, 0x3e, 0x9c, 0x24,
	0xa9, 0x7a, 0x2e, 0x23, 0x7f, 0x49, 0x59, 0x90, 0x47, 0x32, 0x5d, 0x55, 0x3c, 0x0a, 0x5a, 0x4e,
	0x60, 0xde, 0x3f, 0xea, 0x98, 0xcf, 0xd5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x6a, 0xee,
	0x48, 0x41, 0x02, 0x00, 0x00,
}
